language: php

php: ["5.3", "5.4", "5.5", "hhvm"]

matrix:
  allow_failures:
    - php: hhvm

env:
  global:
    - ARCHER_PUBLISH_VERSION=5.5
    - secure: "pTSn8XE11MNuOBzY6d53r/8q20eT+HAtllIOn4q3Jp9nsxlzTx9ORQvwT8LBiDW8TTY87h+TuwawA9AYA/tA0QWPAkI3lD9HqW5/DS0p1aS9ssRywq5KJXs/N8MaqTUfom+RdPkpCwSvAYxWcjy9CXkp+zYVwPPZpg7x2k1rxuY="

install:
  - ./.travis.install

script:
  - ./vendor/bin/archer travis:build
