language: php

matrix:
    include:
        - php: 5.3
        - php: 5.4
        - php: 5.5
        - php: 5.6
        - php: 7.0
        - php: nightly
        - php: hhvm-3.6
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm-3.9
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm-3.12
          sudo: required
          dist: trusty
          group: edge
        - php: hhvm-nightly
          sudo: required
          dist: trusty
          group: edge
    fast_finish: true
    allow_failures:
        - php: nightly
        - php: hhvm-nightly

before_install:
    - phpenv config-rm xdebug.ini || true
    - composer config --global github-oauth.github.com $GITHUB_TOKEN
install: composer install --prefer-dist --no-progress --no-interaction --optimize-autoloader --ignore-platform-reqs
script: scripts/travis
after_script: scripts/travis-after

env:
    global:
        - ELOQUENT_PUBLISH_VERSION=7.0
        - secure: "iei1xR1HrICE/Nps8KztctVcx4H/ss7fX7WbmOLBhm7BVhTTvqF/yfob6ZJUoQp0aWOUcbVOVYk/GLj+gOEyJoWwupsms31shdAcaBHWwTAJHOXFn7a7gtHGxeuOy8nZPvbJsquL/2eas8J5Yrt4KYwnMj2tfASHLkD6gq5mPQA="

cache:
    directories:
        - $HOME/.composer

sudo: false
